ip: 0.0.0.0
ram: 2048
proc: 2
vm_name: centos
vm_box: bento/centos-7.2
nfs: false
synced:
  _options:
    type: vbox  
  folders:
    www:
      host_path: '/Users/dfo5/Sites/'
      guest_path: '/appli/apache/current/'

proxies:
  enable_proxies: true
  http_proxy: 'http://192.168.10.1:8888'
  https_proxy: 'http://192.168.10.1:8888'
  ftp_proxy: 'http://192.168.10.1:8888'
  no_proxy: 'localhost,127.0.0.1,192.168.10.100,10.0.2.15'